language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

env:
  global:
    - ES_VER=0.20.5
    - ES_MAPPER_ATTACHMENTS_VER=1.6.0
    - ES_TRANSPORT_THRIFT_VER=1.4.0

before_script:
  - composer self-update
  - composer --dev install
#  - ./test/bin/install_php_memcache.sh
  - ./test/bin/run_elasticsearch.sh

script:
 - ./vendor/bin/phpunit
